CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Checklists" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "DateCreate" timestamp with time zone NOT NULL,
    "DateClose" timestamp with time zone NOT NULL,
    "TotalPrice" double precision NOT NULL,
    CONSTRAINT "PK_Checklists" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Login" text NOT NULL,
    "Password" text NOT NULL,
    "Name" text NOT NULL,
    "DateOfBirth" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "ChecklistElements" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ChecklistId" integer NOT NULL,
    "Name" text NOT NULL,
    "IsChecked" boolean NOT NULL,
    CONSTRAINT "PK_ChecklistElements" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ChecklistElements_Checklists_ChecklistId" FOREIGN KEY ("ChecklistId") REFERENCES "Checklists" ("Id") ON DELETE CASCADE
);

CREATE TABLE "UserChecklists" (
    "UserId" integer NOT NULL,
    "ChecklistId" integer NOT NULL,
    "IsOwner" boolean NOT NULL,
    CONSTRAINT "PK_UserChecklists" PRIMARY KEY ("UserId", "ChecklistId"),
    CONSTRAINT "FK_UserChecklists_Checklists_ChecklistId" FOREIGN KEY ("ChecklistId") REFERENCES "Checklists" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserChecklists_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_ChecklistElements_ChecklistId" ON "ChecklistElements" ("ChecklistId");

CREATE INDEX "IX_UserChecklists_ChecklistId" ON "UserChecklists" ("ChecklistId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20241026184059_SmartBuyesMigration', '8.0.10');

COMMIT;

